version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: dcalog_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dcalog
      POSTGRES_PASSWORD: dcalog_secret
      POSTGRES_DB: dcalog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
